chore: Establish VPN connection in integration test workflow

diff --git a/.github/workflows/build-integration-test.yaml b/.github/workflows/build-integration-test.yaml
--- a/.github/workflows/build-integration-test.yaml
+++ b/.github/workflows/build-integration-test.yaml
@@ -34,8 +34,26 @@ jobs:
 
       - name: Install dependencies
         run: pnpm install
-        env:
-          CONFIG_URL: ${{ secrets.CONFIG_URL }}
+
+      - name: Establish VPN connection
+        run: |
+          sudo apt update
+          sudo apt install -y openvpn openvpn-systemd-resolved
+          echo 'Configuring the VPN...'
+          echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
+          echo "${{ secrets.VPN_USERNAME }}" > vpn-credentials.txt
+          echo "${{ secrets.VPN_PASSWORD }}" >> vpn-credentials.txt
+          echo 'Connecting to the VPN...'
+          sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon
+          sleep 2
+          echo 'Checking the VPN connection...'
+          STATUS_CODE=$(psql -Atx ${{ secrets.secrets.BORROW_DB_READ_CONNECTION_STRING }} -d oasisborrow -c "SELECT 1;" > /dev/null 2>&1)
+          echo $STATUS_CODE
+          if ! [[ "$STATUS_CODE" =~ ^(0)$ ]]; then
+            echo 'VPN connection failed'
+            exit 1
+          fi
+          echo 'VPN connected!'
 
       - name: Prebuild
         run: pnpm prebuild
