chore: Update VPN connection check in integration test workflow

diff --git a/.github/workflows/build-integration-test.yaml b/.github/workflows/build-integration-test.yaml
--- a/.github/workflows/build-integration-test.yaml
+++ b/.github/workflows/build-integration-test.yaml
@@ -34,7 +34,10 @@ jobs:
 
       - name: Establish VPN connection
         env:
-          BORROW_DB_READ_CONNECTION_STRING: ${{ secrets.BORROW_DB_READ_CONNECTION_STRING }}
+          BORROW_DB_READ_DB: ${{ secrets.BORROW_DB_READ_DB }}
+          BORROW_DB_READ_HOST: ${{ secrets.BORROW_DB_READ_HOST }}
+          BORROW_DB_READ_USER: ${{ secrets.BORROW_DB_READ_USER }}
+          PGPASSWORD: ${{ secrets.BORROW_DB_READ_PASSWORD }}
         run: |
           sudo apt update
           sudo apt install -y openvpn openvpn-systemd-resolved
@@ -45,6 +48,15 @@ jobs:
           echo 'Connecting to the VPN...'
           sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon
           sleep 3
+          echo 'Checking the VPN connection...'
+          /usr/bin/psql -d $BORROW_DB_READ_DB -U $BORROW_DB_READ_USER -h $BORROW_DB_READ_HOST -c 'SELECT 1;
+          STATUS_CODE=$?
+          echo 'Status code: "$STATUS_CODE"'
+          if ! [[ "$STATUS_CODE" = 0 ]]; then
+            echo 'VPN connection failed'
+            exit 1
+          fi
+          echo 'VPN connected!'
 
       - name: Setup tmate session
         uses: mxschmitt/action-tmate@v3
