chore: Update VPN connection check and sleep duration in integration test workflow

diff --git a/.github/workflows/build-unit-test.yaml b/.github/workflows/build-unit-test.yaml
--- a/.github/workflows/build-unit-test.yaml
+++ b/.github/workflows/build-unit-test.yaml
@@ -8,6 +8,8 @@ jobs:
     name: Build and Unit Test
     timeout-minutes: 30
     runs-on: ubuntu-latest
+    env:
+      CONFIG_URL: ${{ secrets.CONFIG_URL }}
     steps:
       - name: Check out code
         uses: actions/checkout@v3
@@ -32,17 +34,44 @@ jobs:
           node-version: 20
           cache: 'pnpm'
 
+      - name: Establish VPN connection
+        run: |
+          sudo apt update
+          sudo apt install -y openvpn openvpn-systemd-resolved
+          echo 'Configuring the VPN...'
+          echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
+          echo "${{ secrets.VPN_USERNAME }}" > vpn-credentials.txt
+          echo "${{ secrets.VPN_PASSWORD }}" >> vpn-credentials.txt
+          echo 'Connecting to the VPN...'
+          sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon
+          sleep 10
+
+      - name: Check VPN connection
+        env:
+          BORROW_DB_READ_DB: ${{ secrets.BORROW_DB_READ_DB }}
+          BORROW_DB_READ_HOST: ${{ secrets.BORROW_DB_READ_HOST }}
+          BORROW_DB_READ_USER: ${{ secrets.BORROW_DB_READ_USER }}
+          BORROW_DB_READ_PASSWORD: ${{ secrets.BORROW_DB_READ_PASSWORD }}
+          PGCONNECT_TIMEOUT: 10
+        run: |
+          echo 'Checking the VPN connection...'
+          sudo systemctl start postgresql.service
+          PGPASSWORD=$BORROW_DB_READ_PASSWORD /usr/bin/psql -d $BORROW_DB_READ_DB -U $BORROW_DB_READ_USER -h $BORROW_DB_READ_HOST -c 'SELECT 1;' > /dev/null
+          STATUS_CODE=$?
+          if ! [[ "$STATUS_CODE" = 0 ]]; then
+            echo 'VPN connection failed'
+            exit 1
+          fi
+          echo 'VPN connected!'
+
       - name: Install dependencies
         run: pnpm install
-        env:
-          CONFIG_URL: ${{ secrets.CONFIG_URL }}
 
       - name: Prebuild
         run: pnpm prebuild
 
       - name: Build
         env:
-          CONFIG_URL: ${{ secrets.CONFIG_URL }}
           BORROW_DB_READ_CONNECTION_STRING: ${{ secrets.BORROW_DB_READ_CONNECTION_STRING }}
         run: pnpm build
 
